"""Wire contract and request authentication for venue edge terminals.

The camera terminal never talks to the GPU service.  It signs an
``edge-ingest.v1`` request to the business gateway; the gateway resolves the
terminal's server-side venue/court/camera binding and relays anonymous video
segments to the GPU service.  Keeping this contract in a small dependency-free
module makes the terminal implementation, API and tests agree on the exact
bytes that are authenticated.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import re
from datetime import datetime, timedelta, timezone
from typing import Any


EDGE_SCHEMA_VERSION = "edge-ingest.v1"
EDGE_TIMESTAMP_HEADER = "X-Edge-Timestamp"
EDGE_NONCE_HEADER = "X-Edge-Nonce"
EDGE_SIGNATURE_HEADER = "X-Edge-Signature"
EDGE_PAYLOAD_SHA256_HEADER = "X-Edge-Payload-SHA256"
MAX_CLOCK_SKEW_SECONDS = 120
NONCE_PATTERN = re.compile(r"^[A-Za-z0-9_-]{16,128}$")
SHA256_PATTERN = re.compile(r"^[a-f0-9]{64}$")


class EdgeContractError(ValueError):
    """A stable, safe-to-return edge protocol validation error."""


def canonical_json_bytes(value: dict[str, Any]) -> bytes:
    """Produce the only JSON representation used in a signed payload hash."""

    return json.dumps(
        value,
        ensure_ascii=False,
        allow_nan=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def payload_sha256(metadata: dict[str, Any], segment_bytes: bytes | None = None) -> str:
    """Hash a JSON request or a multipart metadata-plus-video request.

    Multipart boundaries are generated by HTTP libraries and therefore are not
    stable enough to sign.  For a segment upload we sign canonical metadata,
    one newline delimiter, and the exact segment bytes instead.
    """

    digest = hashlib.sha256()
    digest.update(canonical_json_bytes(metadata))
    if segment_bytes is not None:
        digest.update(b"\n")
        digest.update(segment_bytes)
    return digest.hexdigest()


def derive_device_secret(master_key: str, device_id: str, credential_version: str) -> str:
    """Derive, rather than store, one revocable per-device signing secret."""

    if len(master_key.encode("utf-8")) < 32:
        raise EdgeContractError("edge master key must contain at least 32 bytes")
    message = f"good-badminton-edge.v1:{device_id}:{credential_version}".encode("utf-8")
    derived = hmac.new(master_key.encode("utf-8"), message, hashlib.sha256).digest()
    return base64.urlsafe_b64encode(derived).decode("ascii").rstrip("=")


def signature_input(method: str, path: str, timestamp: str, nonce: str, digest: str) -> bytes:
    return "\n".join((method.upper(), path, timestamp, nonce, digest)).encode("utf-8")


def sign_request(secret: str, method: str, path: str, timestamp: str, nonce: str, digest: str) -> str:
    return hmac.new(
        secret.encode("utf-8"),
        signature_input(method, path, timestamp, nonce, digest),
        hashlib.sha256,
    ).hexdigest()


def parse_timestamp(value: str, *, now: datetime | None = None) -> datetime:
    """Validate RFC3339 UTC time and reject stale/replayed terminal clocks."""

    if not isinstance(value, str) or not value.strip():
        raise EdgeContractError("edge timestamp is required")
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise EdgeContractError("edge timestamp must be RFC3339") from exc
    if parsed.tzinfo is None:
        raise EdgeContractError("edge timestamp must include timezone")
    parsed = parsed.astimezone(timezone.utc)
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    if abs((current - parsed).total_seconds()) > MAX_CLOCK_SKEW_SECONDS:
        raise EdgeContractError("edge timestamp is outside the allowed clock skew")
    return parsed


def validate_nonce(value: str) -> str:
    if not isinstance(value, str) or not NONCE_PATTERN.fullmatch(value):
        raise EdgeContractError("edge nonce must contain 16-128 URL-safe characters")
    return value


def verify_request(
    *,
    secret: str,
    method: str,
    path: str,
    timestamp: str,
    nonce: str,
    digest: str,
    signature: str,
    now: datetime | None = None,
) -> datetime:
    """Verify all replay-resistant request headers and return parsed time."""

    parsed_time = parse_timestamp(timestamp, now=now)
    validate_nonce(nonce)
    if not isinstance(digest, str) or not SHA256_PATTERN.fullmatch(digest):
        raise EdgeContractError("edge payload hash must be a lowercase SHA-256 digest")
    if not isinstance(signature, str) or not SHA256_PATTERN.fullmatch(signature):
        raise EdgeContractError("edge signature must be a lowercase HMAC-SHA256 digest")
    expected = sign_request(secret, method, path, timestamp, nonce, digest)
    if not hmac.compare_digest(expected, signature):
        raise EdgeContractError("edge signature is invalid")
    return parsed_time


def _require_exact_keys(payload: dict[str, Any], allowed: set[str], label: str) -> None:
    extras = set(payload).difference(allowed)
    if extras:
        raise EdgeContractError(f"{label} contains unsupported keys: {sorted(extras)}")


def _id(value: Any, label: str) -> str:
    if not isinstance(value, str) or not 1 <= len(value.strip()) <= 160:
        raise EdgeContractError(f"{label} must be a 1-160 character string")
    return value.strip()


def validate_heartbeat(payload: dict[str, Any]) -> dict[str, Any]:
    _require_exact_keys(
        payload,
        {"schema_version", "device_id", "camera_id", "timestamp", "nonce", "agent_version", "disk_free_bytes", "capture_state", "active_session_id", "last_segment_index"},
        "heartbeat",
    )
    if payload.get("schema_version") != EDGE_SCHEMA_VERSION:
        raise EdgeContractError(f"schema_version must be {EDGE_SCHEMA_VERSION}")
    disk = payload.get("disk_free_bytes")
    last_index = payload.get("last_segment_index")
    if isinstance(disk, bool) or not isinstance(disk, int) or disk < 0:
        raise EdgeContractError("disk_free_bytes must be a non-negative integer")
    if last_index is not None and (isinstance(last_index, bool) or not isinstance(last_index, int) or last_index < 0):
        raise EdgeContractError("last_segment_index must be null or a non-negative integer")
    capture_state = payload.get("capture_state")
    if capture_state not in {"idle", "capturing", "error"}:
        raise EdgeContractError("capture_state must be idle, capturing, or error")
    return {
        "schema_version": EDGE_SCHEMA_VERSION,
        "device_id": _id(payload.get("device_id"), "device_id"),
        "camera_id": _id(payload.get("camera_id"), "camera_id"),
        "timestamp": str(payload.get("timestamp") or ""),
        "nonce": validate_nonce(payload.get("nonce")),
        "agent_version": _id(payload.get("agent_version"), "agent_version"),
        "disk_free_bytes": disk,
        "capture_state": capture_state,
        "active_session_id": None if payload.get("active_session_id") is None else _id(payload.get("active_session_id"), "active_session_id"),
        "last_segment_index": last_index,
    }


def validate_session_start(payload: dict[str, Any]) -> dict[str, Any]:
    _require_exact_keys(
        payload,
        {"schema_version", "device_id", "camera_id", "timestamp", "nonce", "configuration"},
        "session start",
    )
    if payload.get("schema_version") != EDGE_SCHEMA_VERSION:
        raise EdgeContractError(f"schema_version must be {EDGE_SCHEMA_VERSION}")
    configuration = payload.get("configuration")
    if not isinstance(configuration, dict):
        raise EdgeContractError("configuration must be a JSON object")
    # The anonymous GPU request is validated by stream-session.v1 later.  The
    # edge contract intentionally does not carry a player, match or score.
    forbidden = {"user_id", "match_id", "score", "team", "winner", "nickname"}.intersection(configuration)
    if forbidden:
        raise EdgeContractError(f"configuration must not contain business identity fields: {sorted(forbidden)}")
    return {
        "schema_version": EDGE_SCHEMA_VERSION,
        "device_id": _id(payload.get("device_id"), "device_id"),
        "camera_id": _id(payload.get("camera_id"), "camera_id"),
        "timestamp": str(payload.get("timestamp") or ""),
        "nonce": validate_nonce(payload.get("nonce")),
        "configuration": configuration,
    }


def validate_segment_envelope(payload: dict[str, Any]) -> dict[str, Any]:
    _require_exact_keys(
        payload,
        {"schema_version", "device_id", "camera_id", "timestamp", "nonce", "segment"},
        "segment envelope",
    )
    if payload.get("schema_version") != EDGE_SCHEMA_VERSION:
        raise EdgeContractError(f"schema_version must be {EDGE_SCHEMA_VERSION}")
    segment = payload.get("segment")
    if not isinstance(segment, dict):
        raise EdgeContractError("segment must be a JSON object")
    return {
        "schema_version": EDGE_SCHEMA_VERSION,
        "device_id": _id(payload.get("device_id"), "device_id"),
        "camera_id": _id(payload.get("camera_id"), "camera_id"),
        "timestamp": str(payload.get("timestamp") or ""),
        "nonce": validate_nonce(payload.get("nonce")),
        "segment": segment,
    }


def validate_complete_envelope(payload: dict[str, Any]) -> dict[str, Any]:
    _require_exact_keys(
        payload,
        {"schema_version", "device_id", "camera_id", "timestamp", "nonce", "expected_last_segment_index", "allow_partial"},
        "session completion",
    )
    if payload.get("schema_version") != EDGE_SCHEMA_VERSION:
        raise EdgeContractError(f"schema_version must be {EDGE_SCHEMA_VERSION}")
    expected_last = payload.get("expected_last_segment_index")
    if isinstance(expected_last, bool) or not isinstance(expected_last, int) or expected_last < 0:
        raise EdgeContractError("expected_last_segment_index must be a non-negative integer")
    if not isinstance(payload.get("allow_partial"), bool):
        raise EdgeContractError("allow_partial must be a JSON boolean")
    return {
        "schema_version": EDGE_SCHEMA_VERSION,
        "device_id": _id(payload.get("device_id"), "device_id"),
        "camera_id": _id(payload.get("camera_id"), "camera_id"),
        "timestamp": str(payload.get("timestamp") or ""),
        "nonce": validate_nonce(payload.get("nonce")),
        "expected_last_segment_index": expected_last,
        "allow_partial": payload["allow_partial"],
    }


def nonce_expiry(request_time: datetime) -> datetime:
    """Use a short durable nonce TTL; clock skew remains bounded separately."""

    return request_time + timedelta(minutes=10)
