"""Business-owned API for a camera terminal in the no-OSS pilot.

This is deliberately a separate application factory from ``dev_api``.  The
older ``/development`` replay endpoints accept local test video and must not be
mistaken for an authenticated venue ingress endpoint.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import math
import os
import shutil
import subprocess
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol

from fastapi import FastAPI, File, Form, Header, HTTPException, UploadFile
from fastapi.responses import FileResponse

from api.stream_models import validate_configuration, validate_create_request, validate_segment_metadata
from business_gateway.edge_contract import (
    EDGE_NONCE_HEADER,
    EDGE_PAYLOAD_SHA256_HEADER,
    EDGE_SCHEMA_VERSION,
    EDGE_SIGNATURE_HEADER,
    EDGE_TIMESTAMP_HEADER,
    EdgeContractError,
    derive_device_secret,
    nonce_expiry,
    payload_sha256,
    validate_heartbeat,
    validate_complete_envelope,
    validate_segment_envelope,
    validate_session_start,
    verify_request,
)
from business_gateway.streaming import DeliveryLedger, SegmentMetadata, StreamClientConfig, StreamSessionClient


class EdgeRepository(Protocol):
    """Persistence boundary; implementations must bind IDs server-side."""

    def binding(self, device_id: str, camera_id: str) -> dict[str, Any] | None: ...
    def claim_nonce(self, device_id: str, nonce: str, expires_at: datetime) -> bool: ...
    def heartbeat(self, binding: dict[str, Any], payload: dict[str, Any]) -> None: ...
    def capture_control(self, binding: dict[str, Any]) -> dict[str, Any]: ...
    def create_session(self, binding: dict[str, Any], configuration: dict[str, Any]) -> dict[str, Any]: ...
    def session(self, session_id: str) -> dict[str, Any] | None: ...
    def receive_segment(self, session: dict[str, Any], metadata: dict[str, Any]) -> dict[str, Any]: ...
    def mark_forwarded(self, session_id: str, segment_index: int, receipt: dict[str, Any], gpu_session_id: str) -> None: ...
    def mark_segment_failed(self, session_id: str, segment_index: int, message: str) -> None: ...
    def mark_completed(self, session_id: str, gpu_status: str, receipt: dict[str, Any]) -> None: ...


class RollingPreviewStore:
    """Keep a very small, business-server-only window of browser-playable video.

    This is deliberately a preview cache rather than a recording system: the
    latest independently playable MP4 segment replaces older segments after a
    bounded window.  A terminal may later send fMP4 init media and we can add a
    proper LL-HLS playlist without changing the control-plane case model.
    """

    def __init__(self, root: Path, *, max_segments: int = 4) -> None:
        self.root = Path(root)
        self.max_segments = max(1, int(max_segments))

    def _session_root(self, session_id: str) -> Path:
        # Case IDs are UUIDs generated by the business server.  Validate again
        # before using one in a filesystem path.
        return self.root / str(uuid.UUID(session_id))

    def store(self, session_id: str, segment_index: int, content_type: str, video: bytes) -> None:
        if content_type != "video/mp4":
            # Standalone MP4 is the currently supported browser-preview input.
            # fMP4/m4s is still delivered to GPU but needs an init segment
            # before it can be advertised as HLS to a browser.
            return
        session_root = self._session_root(session_id)
        session_root.mkdir(parents=True, exist_ok=True)
        target = session_root / f"{int(segment_index):08d}.mp4"
        target.write_bytes(video)
        segments = sorted(session_root.glob("*.mp4"), key=lambda path: path.name)
        for old in segments[:-self.max_segments]:
            old.unlink(missing_ok=True)

    def latest(self, session_id: str) -> Path | None:
        session_root = self._session_root(session_id)
        if not session_root.is_dir():
            return None
        segments = sorted(session_root.glob("*.mp4"), key=lambda path: path.name)
        return segments[-1] if segments else None


class SessionRecordingStore:
    """Persist independently playable MP4 chunks and seal a full recording."""

    def __init__(self, root: Path, *, ffmpeg_path: str | None = None) -> None:
        self.root = Path(root)
        self.ffmpeg_path = ffmpeg_path or os.environ.get("GOOD_BADMINTON_FFMPEG", "").strip() or shutil.which("ffmpeg")

    def _session_root(self, session_id: str) -> Path:
        return self.root / str(uuid.UUID(session_id))

    def store(self, session_id: str, segment_index: int, content_type: str, video: bytes) -> None:
        if content_type != "video/mp4":
            return
        segment_root = self._session_root(session_id) / "segments"
        segment_root.mkdir(parents=True, exist_ok=True)
        target = segment_root / f"{int(segment_index):08d}.mp4"
        digest = hashlib.sha256(video).hexdigest()
        if target.exists():
            if hashlib.sha256(target.read_bytes()).hexdigest() != digest:
                raise ValueError("recording path already contains a different segment")
            return
        temporary = target.with_suffix(".uploading")
        temporary.write_bytes(video)
        temporary.replace(target)

    def complete(self, session_id: str, expected_last_segment_index: int) -> dict[str, Any]:
        session_root = self._session_root(session_id)
        segment_root = session_root / "segments"
        expected = set(range(int(expected_last_segment_index) + 1))
        segments = self._segments(segment_root)
        missing = sorted(expected.difference(segments))
        if missing:
            return {"status": "incomplete", "missing_segment_indexes": missing}
        recording_path = session_root / "recording.mp4"
        self._assemble(session_root, [segments[index] for index in sorted(expected)], recording_path)
        # ponytail: recordings are retained until an explicit retention policy is agreed; add lifecycle cleanup when storage use requires it.
        return {
            "status": "completed",
            "file_name": "recording.mp4",
            "segment_count": len(expected),
            "sha256": hashlib.sha256(recording_path.read_bytes()).hexdigest(),
        }

    def save_latest_replay(self, session_id: str, seconds: int) -> dict[str, Any]:
        session_root = self._session_root(session_id)
        segments = self._segments(session_root / "segments")
        if not segments:
            raise ValueError("no browser-playable MP4 segments have arrived yet")
        end = max(segments)
        count = max(1, math.ceil(int(seconds) / 2))
        indexes = [end]
        while len(indexes) < count and indexes[0] - 1 in segments:
            indexes.insert(0, indexes[0] - 1)
        replay_id = f"{indexes[0]:08d}-{indexes[-1]:08d}.mp4"
        replay_path = session_root / "replays" / replay_id
        self._assemble(session_root, [segments[index] for index in indexes], replay_path)
        return {
            "id": replay_id,
            "start_segment_index": indexes[0],
            "end_segment_index": indexes[-1],
            "segment_count": len(indexes),
            "estimated_duration_seconds": len(indexes) * 2,
        }

    def list_replays(self, session_id: str) -> list[dict[str, Any]]:
        replay_root = self._session_root(session_id) / "replays"
        if not replay_root.is_dir():
            return []
        replays = []
        for path in sorted(replay_root.glob("*.mp4"), reverse=True):
            try:
                start, end = path.stem.split("-", maxsplit=1)
                replays.append({
                    "id": path.name,
                    "start_segment_index": int(start),
                    "end_segment_index": int(end),
                    "segment_count": int(end) - int(start) + 1,
                    "estimated_duration_seconds": (int(end) - int(start) + 1) * 2,
                })
            except ValueError:
                continue
        return replays

    def replay_path(self, session_id: str, replay_id: str) -> Path:
        if not replay_id.endswith(".mp4") or len(replay_id) != 21:
            raise ValueError("invalid replay id")
        path = self._session_root(session_id) / "replays" / replay_id
        if not path.is_file():
            raise FileNotFoundError(path)
        return path

    @staticmethod
    def _segments(root: Path) -> dict[int, Path]:
        return {
            int(path.stem): path
            for path in root.glob("*.mp4")
            if path.stem.isdigit()
        } if root.is_dir() else {}

    def _assemble(self, session_root: Path, segments: list[Path], output: Path) -> None:
        if output.is_file():
            return
        if not self.ffmpeg_path:
            raise RuntimeError("ffmpeg is required to assemble the retained recording")
        output.parent.mkdir(parents=True, exist_ok=True)
        manifest = session_root / f"{output.stem}.concat.txt"
        manifest.write_text(
            "".join(f"file '{path.relative_to(session_root).as_posix()}'\\n" for path in segments),
            encoding="utf-8",
        )
        temporary = output.with_name(f"{output.stem}.{uuid.uuid4().hex}.partial.mp4")
        try:
            completed = subprocess.run(
                [self.ffmpeg_path, "-nostdin", "-hide_banner", "-loglevel", "error", "-y", "-f", "concat", "-safe", "0",
                 "-i", str(manifest), "-c", "copy", "-movflags", "+faststart", str(temporary)],
                capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=900, check=False,
            )
            if completed.returncode != 0 or not temporary.is_file():
                detail = (completed.stderr or f"ffmpeg did not create {output.name}").strip()[-1000:]
                raise RuntimeError(f"ffmpeg could not assemble the retained recording: {detail}")
            temporary.replace(output)
        finally:
            temporary.unlink(missing_ok=True)


class GpuRelay(Protocol):
    """The only component allowed to make the business-to-GPU network call."""

    def forward(self, session: dict[str, Any], metadata: dict[str, Any], segment_bytes: bytes) -> tuple[str, dict[str, Any]]: ...
    def complete(self, session: dict[str, Any], expected_last_segment_index: int, allow_partial: bool) -> dict[str, Any]: ...

    def events(self, session: dict[str, Any], cursor: str | None, limit: int) -> dict[str, Any]: ...


class PostgresEdgeRepository:
    """Small explicit PostgreSQL adapter for the direct-ingest pilot tables."""

    def __init__(self, database_url: str) -> None:
        self.database_url = database_url.strip()
        if not self.database_url:
            raise ValueError("GOOD_BADMINTON_BUSINESS_DATABASE_URL is required")

    def _connect(self):
        import psycopg
        from psycopg.rows import dict_row

        return psycopg.connect(self.database_url, row_factory=dict_row, autocommit=True)

    def _one(self, query: str, params: tuple[Any, ...]) -> dict[str, Any] | None:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(query, params)
            return cursor.fetchone()

    def binding(self, device_id: str, camera_id: str) -> dict[str, Any] | None:
        return self._one(
            """select d.id::text as device_id, d.venue_id::text as venue_id, d.court_id::text as device_court_id,
                      d.credential_version, d.status as device_status, c.id::text as camera_id,
                      c.court_id::text as court_id, c.status as camera_status,
                      cal.id::text as calibration_id, cal.court_corners
               from business.edge_devices d
               join business.cameras c on c.edge_device_id=d.id
               left join lateral (
                   select id, court_corners from business.camera_calibrations
                   where camera_id=c.id and quality_status='validated'
                   order by version desc limit 1
               ) cal on true
               where d.id=%s and c.id=%s""",
            (device_id, camera_id),
        )

    def claim_nonce(self, device_id: str, nonce: str, expires_at: datetime) -> bool:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute("delete from business.edge_request_nonces where expires_at < now()")
            try:
                cursor.execute(
                    "insert into business.edge_request_nonces (edge_device_id, nonce, expires_at) values (%s, %s, %s)",
                    (device_id, nonce, expires_at),
                )
            except Exception as exc:
                if getattr(exc, "sqlstate", None) == "23505":
                    return False
                raise
        return True

    def heartbeat(self, binding: dict[str, Any], payload: dict[str, Any]) -> None:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                """update business.edge_devices set status='online', last_heartbeat_at=now(),
                          disk_free_bytes=%s, agent_version=%s where id=%s and status <> 'disabled'""",
                (payload["disk_free_bytes"], payload["agent_version"], binding["device_id"]),
            )
            cursor.execute(
                """update business.cameras set status='active', last_heartbeat_at=now()
                   where id=%s and edge_device_id=%s and status <> 'disabled'""",
                (binding["camera_id"], binding["device_id"]),
            )

    def capture_control(self, binding: dict[str, Any]) -> dict[str, Any]:
        """Return the latest server-owned instruction for this bound court.

        A missing row is intentionally safe: newly registered cameras stay in
        heartbeat-only mode until an operator explicitly opens preview or
        capture from the business console.
        """

        row = self._one(
            """select desired_mode, revision, updated_at
               from business.edge_capture_controls where court_id=%s""",
            (binding["court_id"],),
        )
        if not row:
            return {"mode": "idle", "revision": 0, "updated_at": None}
        return {
            "mode": str(row["desired_mode"]),
            "revision": int(row["revision"]),
            "updated_at": str(row["updated_at"]),
        }

    def create_session(self, binding: dict[str, Any], configuration: dict[str, Any]) -> dict[str, Any]:
        session_id = str(uuid.uuid4())
        with self._connect() as connection, connection.cursor() as cursor:
            try:
                cursor.execute(
                    """insert into business.edge_ingest_sessions
                       (id, venue_id, court_id, camera_id, edge_device_id, calibration_id, configuration)
                       values (%s, %s, %s, %s, %s, %s, %s::jsonb)""",
                    (
                        session_id, binding["venue_id"], binding["court_id"], binding["camera_id"],
                        binding["device_id"], binding["calibration_id"], json.dumps(configuration, ensure_ascii=False),
                    ),
                )
            except Exception as exc:
                if getattr(exc, "sqlstate", None) == "23505":
                    raise ValueError("camera already has an active edge ingest session") from exc
                raise
        return self.session(session_id) or {}

    def session(self, session_id: str) -> dict[str, Any] | None:
        return self._one(
            """select s.id::text as id, s.venue_id::text as venue_id, s.court_id::text as court_id,
                      s.camera_id::text as camera_id, s.edge_device_id::text as device_id,
                      s.calibration_id::text as calibration_id, s.status, s.gpu_analysis_session_id,
                      s.gpu_status, s.configuration, s.received_segment_count, s.forwarded_segment_count,
                      s.last_segment_index, s.last_received_at, s.last_forwarded_at, s.error_code, s.error_message,
                      s.gpu_forwarding_enabled, s.preview_available, s.last_preview_at, s.gpu_event_cursor,
                      cal.court_corners
               from business.edge_ingest_sessions s
               left join business.camera_calibrations cal on cal.id=s.calibration_id
               where s.id=%s""",
            (session_id,),
        )

    def receive_segment(self, session: dict[str, Any], metadata: dict[str, Any]) -> dict[str, Any]:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                """select id::text, sha256, idempotency_key, status, gpu_receipt
                   from business.edge_ingest_segments where edge_ingest_session_id=%s and segment_index=%s""",
                (session["id"], metadata["segment_index"]),
            )
            existing = cursor.fetchone()
            if existing:
                if existing["sha256"] != metadata["sha256"] or existing["idempotency_key"] != metadata["idempotency_key"]:
                    raise ValueError("segment index conflicts with a different hash or idempotency key")
                return {**existing, "reused": True}
            segment_id = str(uuid.uuid4())
            cursor.execute(
                """insert into business.edge_ingest_segments
                   (id, edge_ingest_session_id, segment_index, source_start_time_sec, duration_sec, sha256,
                    content_type, content_length_bytes, idempotency_key)
                   values (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
                (segment_id, session["id"], metadata["segment_index"], metadata["source_start_time_sec"],
                 metadata["duration_sec"], metadata["sha256"], metadata["content_type"],
                 metadata["content_length_bytes"], metadata["idempotency_key"]),
            )
            cursor.execute(
                """update business.edge_ingest_sessions set status='receiving',
                          received_segment_count=received_segment_count+1, last_segment_index=%s,
                          last_received_at=now(), error_code=null, error_message=null where id=%s""",
                (metadata["segment_index"], session["id"]),
            )
        return {"id": segment_id, "status": "received", "reused": False, "gpu_receipt": {}}

    def mark_forwarded(self, session_id: str, segment_index: int, receipt: dict[str, Any], gpu_session_id: str) -> None:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                """update business.edge_ingest_segments set status='forwarded', gpu_receipt=%s::jsonb,
                          forwarded_at=now(), error_code=null, error_message=null
                   where edge_ingest_session_id=%s and segment_index=%s""",
                (json.dumps(receipt, ensure_ascii=False), session_id, segment_index),
            )
            cursor.execute(
                """update business.edge_ingest_sessions set status='processing', gpu_analysis_session_id=%s,
                          gpu_status='accepted', forwarded_segment_count=(select count(*) from business.edge_ingest_segments
                              where edge_ingest_session_id=%s and status='forwarded'), last_forwarded_at=now(),
                          error_code=null, error_message=null where id=%s""",
                (gpu_session_id, session_id, session_id),
            )

    def mark_segment_failed(self, session_id: str, segment_index: int, message: str) -> None:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                """update business.edge_ingest_segments set status='failed', error_code='gpu_forward_failed', error_message=%s
                   where edge_ingest_session_id=%s and segment_index=%s""",
                (message[:1000], session_id, segment_index),
            )
            cursor.execute(
                """update business.edge_ingest_sessions set status='relaying', error_code='gpu_forward_failed',
                   error_message=%s where id=%s""",
                (message[:1000], session_id),
            )

    def mark_completed(self, session_id: str, gpu_status: str, receipt: dict[str, Any]) -> None:
        status_map = {"finalized": "succeeded", "partial": "partial", "cancelled": "cancelled", "failed": "failed"}
        status = status_map.get(gpu_status, "processing")
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                """update business.edge_ingest_sessions set status=%s, gpu_status=%s,
                          finished_at=case when %s in ('succeeded', 'partial', 'failed', 'cancelled') then now() else null end,
                          error_code=case when %s='failed' then 'gpu_completion_failed' else null end,
                          error_message=case when %s='failed' then %s else null end where id=%s""",
                (status, gpu_status, status, status, status, json.dumps(receipt, ensure_ascii=False)[:1000], session_id),
            )

    def mark_preview_available(self, session_id: str) -> None:
        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(
                """update business.edge_ingest_sessions set preview_available=true, last_preview_at=now(),
                          status=case when status='requested' then 'receiving' else status end where id=%s""",
                (session_id,),
            )

    def record_gpu_events(self, session_id: str, response: dict[str, Any]) -> None:
        events = response.get("events") or []
        if not isinstance(events, list):
            events = []
        with self._connect() as connection, connection.cursor() as cursor:
            for event in events:
                if not isinstance(event, dict):
                    continue
                event_id = str(event.get("event_id") or uuid.uuid4())
                raw_level = str(event.get("level") or "info").lower()
                level = raw_level if raw_level in {"debug", "info", "warning", "error"} else "info"
                cursor.execute(
                    """insert into business.edge_ingest_event_logs
                       (id, edge_ingest_session_id, source, event_id, level, event_type, message, payload)
                       values (%s, %s, 'gpu', %s, %s, %s, %s, %s::jsonb)
                       on conflict (edge_ingest_session_id, source, event_id) do nothing""",
                    (str(uuid.uuid4()), session_id, event_id, level, str(event.get("event_type") or event.get("type") or "gpu_event"),
                     str(event.get("message") or "")[:2000], json.dumps(event, ensure_ascii=False)),
                )
            cursor.execute(
                "update business.edge_ingest_sessions set gpu_event_cursor=%s where id=%s",
                (response.get("next_cursor"), session_id),
            )


class StreamSessionGpuRelay:
    """Temporary-disk relay that uses the existing receipt-aware GPU client."""

    def __init__(self, staging_root: Path, *, config: StreamClientConfig | None = None) -> None:
        self.staging_root = Path(staging_root)
        self.config = config

    def forward(self, session: dict[str, Any], metadata: dict[str, Any], segment_bytes: bytes) -> tuple[str, dict[str, Any]]:
        expected_hash = hashlib.sha256(segment_bytes).hexdigest()
        if expected_hash != metadata["sha256"] or len(segment_bytes) != metadata["content_length_bytes"]:
            raise ValueError("segment bytes do not match declared hash or length")
        session_root = self.staging_root / session["id"]
        session_root.mkdir(parents=True, exist_ok=True)
        extension = ".mp4" if metadata["content_type"] == "video/mp4" else ".m4s"
        segment_path = session_root / f"{metadata['segment_index']:08d}{extension}"
        if segment_path.exists() and hashlib.sha256(segment_path.read_bytes()).hexdigest() != expected_hash:
            raise ValueError("staging path already contains a different segment")
        if not segment_path.exists():
            segment_path.write_bytes(segment_bytes)
        client = StreamSessionClient(
            self.config or StreamClientConfig.from_environment(),
            DeliveryLedger(session_root / "delivery-ledger.json"),
        )
        create_request = validate_create_request({
            "schema_version": "stream-session.v1",
            "camera_id": session["camera_id"],
            "calibration_id": session["calibration_id"],
            "court_corners": session["court_corners"],
            "analysis_mode": "person_only",
            "client_reference": session["id"],
            "configuration": session["configuration"],
        })
        created = client.create_session(create_request, idempotency_key=f"edge-session-{session['id']}")
        gpu_session_id = str(created["analysis_session_id"])
        safe_metadata = dict(metadata)
        safe_metadata["court_corners"] = session["court_corners"]
        receipt = client.submit_segment(segment_path, SegmentMetadata(**safe_metadata))
        segment_path.unlink(missing_ok=True)
        # Keep the ledger but remove an empty raw-video staging leaf where the
        # OS allows it.  Ledger records are non-video operational evidence.
        if not any(path.suffix in {".mp4", ".m4s"} for path in session_root.iterdir()):
            pass
        return gpu_session_id, receipt

    def complete(self, session: dict[str, Any], expected_last_segment_index: int, allow_partial: bool) -> dict[str, Any]:
        session_root = self.staging_root / session["id"]
        client = StreamSessionClient(
            self.config or StreamClientConfig.from_environment(),
            DeliveryLedger(session_root / "delivery-ledger.json"),
        )
        return client.complete(expected_last_segment_index, allow_partial=allow_partial)

    def events(self, session: dict[str, Any], cursor: str | None, limit: int) -> dict[str, Any]:
        session_root = self.staging_root / session["id"]
        client = StreamSessionClient(
            self.config or StreamClientConfig.from_environment(),
            DeliveryLedger(session_root / "delivery-ledger.json"),
        )
        return client.read_events(cursor=cursor, limit=limit)


def _http_error(status: int, message: str) -> HTTPException:
    return HTTPException(status_code=status, detail={"code": "edge_ingest_rejected", "message": message})


def create_edge_app(
    repository: EdgeRepository,
    relay: GpuRelay,
    *,
    edge_master_key: str | None = None,
    preview_store: RollingPreviewStore | None = None,
    recording_store: SessionRecordingStore | None = None,
) -> FastAPI:
    """Create the deployable ingress app; callers inject DB and GPU adapters."""

    master_key = (edge_master_key or os.environ.get("GOOD_BADMINTON_EDGE_MASTER_KEY", "")).strip()
    if len(master_key.encode("utf-8")) < 32:
        raise ValueError("GOOD_BADMINTON_EDGE_MASTER_KEY must contain at least 32 bytes")
    app = FastAPI(title="Good-Badminton Edge Ingest Gateway", version="1.0")

    def authenticate_operator(key: str) -> None:
        if not hmac.compare_digest(key, master_key):
            raise _http_error(403, "operator request is not authorized")

    def authenticate(
        *, method: str, path: str, device_id: str, camera_id: str, payload: dict[str, Any],
        timestamp: str, nonce: str, digest: str, signature: str, segment_bytes: bytes | None = None,
    ) -> dict[str, Any]:
        if payload.get("device_id") != device_id:
            raise _http_error(403, "path device_id does not match payload")
        if payload.get("timestamp") != timestamp or payload.get("nonce") != nonce:
            raise _http_error(401, "signed timestamp or nonce does not match request body")
        computed_digest = payload_sha256(payload, segment_bytes)
        if computed_digest != digest:
            raise _http_error(401, "payload hash does not match request body")
        binding = repository.binding(device_id, camera_id)
        if not binding or binding.get("device_status") == "disabled" or binding.get("camera_status") == "disabled":
            raise _http_error(403, "device/camera binding is not enabled")
        try:
            request_time = verify_request(
                secret=derive_device_secret(master_key, device_id, str(binding["credential_version"])),
                method=method, path=path, timestamp=timestamp, nonce=nonce, digest=digest, signature=signature,
            )
        except EdgeContractError as exc:
            raise _http_error(401, str(exc)) from exc
        if not repository.claim_nonce(device_id, nonce, nonce_expiry(request_time)):
            raise _http_error(409, "edge nonce was already used")
        return binding

    @app.get("/api/v1/health")
    def health():
        return {"status": "ready", "service": "edge-ingest", "schema_version": EDGE_SCHEMA_VERSION}

    @app.post("/api/v1/edge/devices/{device_id}/heartbeats")
    def heartbeat(
        device_id: str, body: dict[str, Any],
        x_edge_timestamp: str = Header(..., alias=EDGE_TIMESTAMP_HEADER),
        x_edge_nonce: str = Header(..., alias=EDGE_NONCE_HEADER),
        x_edge_payload_sha256: str = Header(..., alias=EDGE_PAYLOAD_SHA256_HEADER),
        x_edge_signature: str = Header(..., alias=EDGE_SIGNATURE_HEADER),
    ):
        try:
            payload = validate_heartbeat(body)
            binding = authenticate(method="POST", path=f"/api/v1/edge/devices/{device_id}/heartbeats", device_id=device_id,
                camera_id=payload["camera_id"], payload=payload, timestamp=x_edge_timestamp, nonce=x_edge_nonce,
                digest=x_edge_payload_sha256, signature=x_edge_signature)
            repository.heartbeat(binding, payload)
            capture_control = repository.capture_control(binding)
        except EdgeContractError as exc:
            raise _http_error(422, str(exc)) from exc
        return {
            "status": "accepted", "device_id": device_id, "court_id": binding["court_id"],
            "capture_control": capture_control,
        }

    @app.post("/api/v1/edge/devices/{device_id}/sessions", status_code=202)
    def start_session(
        device_id: str, body: dict[str, Any],
        x_edge_timestamp: str = Header(..., alias=EDGE_TIMESTAMP_HEADER),
        x_edge_nonce: str = Header(..., alias=EDGE_NONCE_HEADER),
        x_edge_payload_sha256: str = Header(..., alias=EDGE_PAYLOAD_SHA256_HEADER),
        x_edge_signature: str = Header(..., alias=EDGE_SIGNATURE_HEADER),
    ):
        try:
            payload = validate_session_start(body)
            binding = authenticate(method="POST", path=f"/api/v1/edge/devices/{device_id}/sessions", device_id=device_id,
                camera_id=payload["camera_id"], payload=payload, timestamp=x_edge_timestamp, nonce=x_edge_nonce,
                digest=x_edge_payload_sha256, signature=x_edge_signature)
            capture_mode = repository.capture_control(binding).get("mode")
            if capture_mode == "idle":
                raise ValueError("business server has not enabled capture for this court")
            if binding.get("calibration_id"):
                # Validate the exact anonymous GPU configuration before
                # creating an analysis-ready business session.
                normalized_configuration = validate_create_request({
                    "schema_version": "stream-session.v1",
                    "camera_id": binding["camera_id"],
                    "calibration_id": binding["calibration_id"],
                    "court_corners": binding["court_corners"],
                    "analysis_mode": "person_only",
                    "client_reference": f"edge-config-{device_id}",
                    "configuration": payload["configuration"],
                })["configuration"]
                ingest_mode = "analysis_ready"
            else:
                # A signed terminal can establish a short preview so the
                # operator can mark the four real image corners. It remains
                # impossible to relay this session to GPU.
                if capture_mode != "preview":
                    raise ValueError("camera has no validated calibration; start preview, save four corners, then start record")
                normalized_configuration = validate_configuration(payload["configuration"])
                ingest_mode = "preview_only"
            session = repository.create_session(binding, normalized_configuration)
        except EdgeContractError as exc:
            raise _http_error(422, str(exc)) from exc
        except ValueError as exc:
            raise _http_error(409, str(exc)) from exc
        return {"status": "accepted", "edge_ingest_session_id": session["id"], "court_id": session["court_id"], "ingest_mode": ingest_mode,
                "delivery_mode": "preview_only" if ingest_mode == "preview_only" else "business_to_gpu_direct"}

    @app.post("/api/v1/edge/sessions/{session_id}/segments/{segment_index}", status_code=202)
    async def upload_segment(
        session_id: str, segment_index: int, segment: UploadFile = File(...), metadata: str = Form(...),
        x_edge_timestamp: str = Header(..., alias=EDGE_TIMESTAMP_HEADER),
        x_edge_nonce: str = Header(..., alias=EDGE_NONCE_HEADER),
        x_edge_payload_sha256: str = Header(..., alias=EDGE_PAYLOAD_SHA256_HEADER),
        x_edge_signature: str = Header(..., alias=EDGE_SIGNATURE_HEADER),
    ):
        try:
            envelope = validate_segment_envelope(json.loads(metadata))
            if envelope["segment"].get("segment_index") != segment_index:
                raise EdgeContractError("path segment_index does not match metadata")
            stored = repository.session(session_id)
            if not stored:
                raise _http_error(404, "edge ingest session was not found")
            if stored["device_id"] != envelope["device_id"] or stored["camera_id"] != envelope["camera_id"]:
                raise _http_error(403, "session does not belong to this device/camera")
            video = await segment.read()
            binding = authenticate(method="POST", path=f"/api/v1/edge/sessions/{session_id}/segments/{segment_index}",
                device_id=envelope["device_id"], camera_id=envelope["camera_id"], payload=envelope,
                timestamp=x_edge_timestamp, nonce=x_edge_nonce, digest=x_edge_payload_sha256,
                signature=x_edge_signature, segment_bytes=video)
            del binding  # Binding check occurs before any GPU/network action.
            segment_metadata = validate_segment_metadata(envelope["segment"])
            if hashlib.sha256(video).hexdigest() != segment_metadata["sha256"] or len(video) != segment_metadata["content_length_bytes"]:
                raise EdgeContractError("segment bytes do not match metadata")
            if stored.get("calibration_id") and segment_metadata["court_corners"] != stored["court_corners"]:
                raise EdgeContractError("terminal court_corners do not match the server-validated calibration")
            record = repository.receive_segment(stored, segment_metadata)
            if recording_store:
                recording_store.store(session_id, segment_index, segment_metadata["content_type"], video)
            if record["status"] == "forwarded":
                return {"status": "accepted", "reused": True, "gpu_receipt": record["gpu_receipt"]}
            if preview_store:
                preview_store.store(session_id, segment_index, segment_metadata["content_type"], video)
                if hasattr(repository, "mark_preview_available"):
                    repository.mark_preview_available(session_id)
            # GPU delivery is controlled per case by an operator.  Video keeps
            # arriving at the business gateway for the live preview while this
            # flag is off; only future segments are forwarded after it is on.
            if not stored.get("calibration_id"):
                return {
                    "status": "preview_available",
                    "reused": bool(record["reused"]),
                    "edge_ingest_session_id": session_id,
                    "gpu_forwarding": "blocked_pending_calibration",
                    "message": "视频预览已更新；请先在业务后台保存并验证球场四角，才可开启 GPU 推送。",
                }
            if not bool(stored.get("gpu_forwarding_enabled", True)):
                return {
                    "status": "preview_available",
                    "reused": bool(record["reused"]),
                    "edge_ingest_session_id": session_id,
                    "gpu_forwarding": "paused",
                    "message": "视频预览已更新；GPU 推送由运营后台开启后才会处理后续片段。",
                }
            gpu_session_id, receipt = relay.forward(stored, segment_metadata, video)
            repository.mark_forwarded(session_id, segment_index, receipt, gpu_session_id)
            return {"status": "accepted", "reused": bool(record["reused"]), "gpu_analysis_session_id": gpu_session_id, "gpu_receipt": receipt}
        except HTTPException:
            raise
        except (EdgeContractError, ValueError, json.JSONDecodeError) as exc:
            raise _http_error(422, str(exc)) from exc
        except Exception as exc:
            try:
                repository.mark_segment_failed(session_id, segment_index, str(exc))
            except Exception:
                pass
            raise _http_error(502, "business gateway did not receive a GPU receipt; retry the same segment") from exc

    @app.post("/api/v1/edge/sessions/{session_id}/complete", status_code=202)
    def complete_session(
        session_id: str, body: dict[str, Any],
        x_edge_timestamp: str = Header(..., alias=EDGE_TIMESTAMP_HEADER),
        x_edge_nonce: str = Header(..., alias=EDGE_NONCE_HEADER),
        x_edge_payload_sha256: str = Header(..., alias=EDGE_PAYLOAD_SHA256_HEADER),
        x_edge_signature: str = Header(..., alias=EDGE_SIGNATURE_HEADER),
    ):
        try:
            payload = validate_complete_envelope(body)
            stored = repository.session(session_id)
            if not stored:
                raise _http_error(404, "edge ingest session was not found")
            if stored["device_id"] != payload["device_id"] or stored["camera_id"] != payload["camera_id"]:
                raise _http_error(403, "session does not belong to this device/camera")
            authenticate(method="POST", path=f"/api/v1/edge/sessions/{session_id}/complete", device_id=payload["device_id"],
                camera_id=payload["camera_id"], payload=payload, timestamp=x_edge_timestamp, nonce=x_edge_nonce,
                digest=x_edge_payload_sha256, signature=x_edge_signature)
            recording = (
                recording_store.complete(session_id, payload["expected_last_segment_index"])
                if recording_store else {"status": "not_configured"}
            )
            # A pilot court is allowed to stop a capture before the operator
            # enables GPU forwarding.  It has no upstream GPU session to
            # complete, but the edge session must still leave the active-set
            # so a restarted venue relay can start a new capture.
            if (not bool(stored.get("gpu_forwarding_enabled", True))
                    and not stored.get("gpu_analysis_session_id")):
                receipt = {"status": "cancelled", "reason": "gpu_forwarding_was_not_enabled"}
                repository.mark_completed(session_id, "cancelled", receipt)
                return {"status": "accepted", "edge_ingest_session_id": session_id,
                        "gpu_status": "cancelled", "gpu_receipt": receipt, "recording": recording}
            receipt = relay.complete(stored, payload["expected_last_segment_index"], payload["allow_partial"])
            gpu_status = str(receipt.get("status") or "processing")
            repository.mark_completed(session_id, gpu_status, receipt)
            return {"status": "accepted", "edge_ingest_session_id": session_id, "gpu_status": gpu_status,
                    "gpu_receipt": receipt, "recording": recording}
        except HTTPException:
            raise
        except (EdgeContractError, ValueError) as exc:
            raise _http_error(422, str(exc)) from exc
        except Exception as exc:
            raise _http_error(502, "business gateway could not complete the GPU session; retry the same completion request") from exc

    @app.get("/api/v1/edge/sessions/{session_id}")
    def session_status(session_id: str):
        session = repository.session(session_id)
        if not session:
            raise _http_error(404, "edge ingest session was not found")
        return {"session": session}

    @app.get("/api/v1/edge/sessions/{session_id}/preview/latest.mp4")
    def latest_preview(session_id: str):
        """Serve the latest short preview segment from the business server.

        Deploy this internal endpoint behind the operator reverse proxy.  It
        deliberately has no camera or RTSP URL in either the request or reply.
        """
        if not repository.session(session_id):
            raise _http_error(404, "edge ingest session was not found")
        if not preview_store:
            raise _http_error(503, "live preview cache is not configured")
        try:
            segment_path = preview_store.latest(session_id)
        except ValueError:
            raise _http_error(404, "edge ingest session was not found") from None
        if not segment_path:
            raise _http_error(404, "no browser-playable preview segment has arrived yet")
        return FileResponse(segment_path, media_type="video/mp4", headers={"Cache-Control": "no-store"})

    @app.post("/api/v1/edge/sessions/{session_id}/replays", status_code=201)
    def save_replay(session_id: str, body: dict[str, Any], x_operator_edge_key: str = Header(...)):
        authenticate_operator(x_operator_edge_key)
        if not repository.session(session_id):
            raise _http_error(404, "edge ingest session was not found")
        seconds = body.get("seconds", 20)
        if isinstance(seconds, bool) or not isinstance(seconds, int) or not 2 <= seconds <= 120:
            raise _http_error(422, "seconds must be an integer between 2 and 120")
        if not recording_store:
            raise _http_error(503, "recording storage is not configured")
        try:
            return {"replay": recording_store.save_latest_replay(session_id, seconds)}
        except ValueError as exc:
            raise _http_error(409, str(exc)) from exc

    @app.get("/api/v1/edge/sessions/{session_id}/replays")
    def list_replays(session_id: str, x_operator_edge_key: str = Header(...)):
        authenticate_operator(x_operator_edge_key)
        if not repository.session(session_id):
            raise _http_error(404, "edge ingest session was not found")
        if not recording_store:
            raise _http_error(503, "recording storage is not configured")
        return {"replays": recording_store.list_replays(session_id)}

    @app.get("/api/v1/edge/sessions/{session_id}/replays/{replay_id}")
    def play_replay(session_id: str, replay_id: str, x_operator_edge_key: str = Header(...)):
        authenticate_operator(x_operator_edge_key)
        if not repository.session(session_id):
            raise _http_error(404, "edge ingest session was not found")
        if not recording_store:
            raise _http_error(503, "recording storage is not configured")
        try:
            return FileResponse(recording_store.replay_path(session_id, replay_id), media_type="video/mp4",
                                headers={"Cache-Control": "private, no-store"})
        except (ValueError, FileNotFoundError):
            raise _http_error(404, "saved replay was not found") from None

    @app.get("/api/v1/edge/sessions/{session_id}/gpu-events")
    def gpu_events(session_id: str, limit: int = 100):
        session = repository.session(session_id)
        if not session:
            raise _http_error(404, "edge ingest session was not found")
        if not session.get("gpu_analysis_session_id"):
            return {"case_id": session_id, "gpu_analysis_session_id": None, "events": [], "next_cursor": None,
                    "message": "尚未向 GPU 推送片段。"}
        response = relay.events(session, session.get("gpu_event_cursor") or None, max(1, min(limit, 500)))
        if hasattr(repository, "record_gpu_events"):
            repository.record_gpu_events(session_id, response)
        return {"case_id": session_id, "gpu_analysis_session_id": session["gpu_analysis_session_id"], **response}

    return app


def create_production_edge_app() -> FastAPI:
    """Environment-based entry point used only by the future deployment unit."""

    database_url = os.environ.get("GOOD_BADMINTON_BUSINESS_DATABASE_URL", "")
    staging_root = Path(os.environ.get("GOOD_BADMINTON_EDGE_STAGING_DIR", "outputs/edge_staging"))
    preview_root = Path(os.environ.get("GOOD_BADMINTON_EDGE_PREVIEW_DIR", "outputs/edge_preview"))
    recording_root = Path(os.environ.get("GOOD_BADMINTON_EDGE_RECORDING_DIR", "outputs/edge_recordings"))
    return create_edge_app(
        PostgresEdgeRepository(database_url),
        StreamSessionGpuRelay(staging_root),
        preview_store=RollingPreviewStore(preview_root),
        recording_store=SessionRecordingStore(recording_root),
    )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(create_production_edge_app(), host=os.environ.get("GOOD_BADMINTON_BUSINESS_HOST", "127.0.0.1"), port=int(os.environ.get("GOOD_BADMINTON_BUSINESS_PORT", "8080")))
